[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027917431090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8c61c670a5132ebb939385a0851cadaa
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027917427210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8c61c670a5132ebb939385a0851cadaa
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027917449990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8c61c670a5132ebb939385a0851cadaa