[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002059C29E790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b11a848fedb01b2985af5192fd516fe9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002059C29EDD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b11a848fedb01b2985af5192fd516fe9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002059C2BAA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b11a848fedb01b2985af5192fd516fe9